/**
 * Export Generator Provenance — PDF composer tests. Same mocking
 * discipline as the sibling AdaptiveResearchDocument.spec.tsx (react-pdf
 * primitives mocked to plain string tags; the real composer/JSX runs
 * unmocked).
 */

import { AdaptiveResearchExportV1 } from "@/lib/adaptiveSchema/researchExport";
import { extractPdfElementText } from "./testUtils";

jest.mock("@react-pdf/renderer", () => ({
  Document: "DOCUMENT",
  Page: "PAGE",
  View: "VIEW",
  Text: "TEXT",
  StyleSheet: { create: (styles: unknown) => styles },
  renderToBuffer: jest.fn(),
}));

import { AdaptiveResearchDocument } from "@/lib/pdf/AdaptiveResearchDocument";

function baseRecord(overrides: Partial<AdaptiveResearchExportV1> = {}): AdaptiveResearchExportV1 {
  return {
    version: 1,
    exportId: "exp-prov-pdf-1",
    runId: "run-prov-pdf-1",
    schemaId: "comparison_matrix",
    schemaFamily: "milestone2",
    schemaVersion: 1,
    reportVersion: 1,
    createdAt: "2026-01-02T00:00:00.000Z",
    createdBy: "uid-should-never-render-into-pdf",
    format: "pdf",
    artifactStatus: "ready",
    classification: "internal",
    governanceStatusAtExport: { family: "milestone2", kind: "approved", isOwnerOverride: false },
    reportSnapshot: {
      question: "Test question?",
      models: [{ modelId: "chatgpt" as any, ok: true }],
      reportTypeLabel: "Comparison Report",
      consensusLevel: "moderate",
      sourceGroundingLevel: "strong",
      reportGeneratedAt: "2026-01-01T00:00:00.000Z",
      milestone2: {
        schemaId: "comparison_matrix",
        result: {},
        meta: {} as any,
        decisionReceipt: {
          conclusion: "Test conclusion text.",
          basis: [],
          assumptions: [],
          uncertainties: [],
          limitations: [],
          sources: [],
          sourceBacked: false,
          humanReviewNeeded: false,
        },
      },
    },
    exportMetadata: {
      exportId: "exp-prov-pdf-1",
      runId: "run-prov-pdf-1",
      schemaVersion: 1,
      exportedSections: ["reportSnapshot.milestone2"],
      createdAt: "2026-01-02T00:00:00.000Z",
      requestingUser: "uid-should-never-render-into-pdf",
      finalReportVersion: 1,
    },
    ...overrides,
  };
}

describe("AdaptiveResearchDocument — generator provenance (PDF)", () => {
  it("renders 'Generated by' and 'Email' when the record has a frozen generatedBy", () => {
    const record = baseRecord({ generatedBy: { displayName: "Yasin Warsame", maskedEmail: "ya***@gmail.com" } });
    const text = extractPdfElementText(AdaptiveResearchDocument({ record }));
    expect(text).toContain("Generated by");
    expect(text).toContain("Yasin Warsame");
    expect(text).toContain("Email");
    expect(text).toContain("ya***@gmail.com");
  });

  it("renders only the displayName line, omits the Email line, when maskedEmail is null", () => {
    const record = baseRecord({ generatedBy: { displayName: "ConvergePanel user", maskedEmail: null } });
    const text = extractPdfElementText(AdaptiveResearchDocument({ record }));
    expect(text).toContain("ConvergePanel user");
    expect(text).not.toContain("Email");
  });

  it("V1 compatibility: renders nothing extra (no 'Generated by' label at all) when generatedBy is absent", () => {
    const record = baseRecord(); // no generatedBy override
    const text = extractPdfElementText(AdaptiveResearchDocument({ record }));
    expect(text).not.toContain("Generated by");
  });

  it("privacy: never renders the raw uid anywhere in the PDF, even though generatedBy is present", () => {
    const record = baseRecord({ generatedBy: { displayName: "Yasin Warsame", maskedEmail: "ya***@gmail.com" } });
    const text = extractPdfElementText(AdaptiveResearchDocument({ record }));
    expect(text).not.toContain("uid-should-never-render-into-pdf");
  });

  it("privacy: never renders the full unmasked email, only the masked form", () => {
    const record = baseRecord({ generatedBy: { displayName: "Yasin Warsame", maskedEmail: "ya***@gmail.com" } });
    const text = extractPdfElementText(AdaptiveResearchDocument({ record }));
    expect(text).not.toContain("yasinwarsame@gmail.com");
    expect(text).toContain("ya***@gmail.com");
  });

  it("layout: works correctly with a long display name and long email domain (no crash, both render)", () => {
    const record = baseRecord({
      generatedBy: { displayName: "Alexandria Montgomery-Fitzgerald the Third of Testington", maskedEmail: "al***@a-very-long-enterprise-subdomain.example.co.uk" },
    });
    const text = extractPdfElementText(AdaptiveResearchDocument({ record }));
    expect(text).toContain("Alexandria Montgomery-Fitzgerald the Third of Testington");
    expect(text).toContain("al***@a-very-long-enterprise-subdomain.example.co.uk");
  });

  it("Document-level author metadata stays hardcoded to 'ConvergePanel' — never the generator's name or email, even when generatedBy is present", () => {
    const record = baseRecord({ generatedBy: { displayName: "Yasin Warsame", maskedEmail: "ya***@gmail.com" } });
    const element = AdaptiveResearchDocument({ record }) as any;
    expect(element.props.author).toBe("ConvergePanel");
  });
});
