/**
 * TEAM-VERIFICATION-PARITY-R2 — the SHARED, read-only Claim and Video result
 * views. Real component rendering (react-test-renderer). Every Personal
 * boundary is a recording or throwing mock, so a view that reached for auth,
 * governance, the viewer's plan, memo export or the network fails here.
 */

jest.mock("next/link", () => ({
  __esModule: true,
  default: ({ href, children, className }: Record<string, unknown>) => require("react").createElement("a", { href, className }, children as never),
}));
const mockedUseAuth = jest.fn(() => ({ user: { uid: "u", email: "u@example.com" }, authReady: true }));
jest.mock("@/components/AuthProvider", () => ({ useAuth: () => mockedUseAuth() }));
const mockedAuthedFetch = jest.fn();
jest.mock("@/lib/client/authedFetch", () => ({ authedFetch: (...a: unknown[]) => mockedAuthedFetch(...a) }));
const mockedUseUserPlan = jest.fn(() => ({ plan: "pro", governanceAssignedReviewerEmail: null }));
jest.mock("@/hooks/useUserPlan", () => ({ useUserPlan: () => mockedUseUserPlan() }));
const mockedGenerateMemo = jest.fn(() => "MEMO");
const mockedDownloadTextFile = jest.fn();
jest.mock("@/lib/verification/generateMemo", () => ({
  generateVerificationMemo: (...a: unknown[]) => (mockedGenerateMemo as unknown as (...x: unknown[]) => string)(...a),
  downloadTextFile: (...a: unknown[]) => mockedDownloadTextFile(...a),
}));

import { createElement, type ReactNode } from "react";
import * as fs from "fs";
import * as path from "path";
import TestRenderer, { act } from "react-test-renderer";
import ClaimVerificationResultView, { buildClaimVerdictClipboardText, ClaimVerificationAuditTrailDetails } from "@/components/verification/ClaimVerificationResultView";
import VideoVerificationResultView, { buildVideoVerdictClipboardText, VideoVerificationAuditTrailDetails } from "@/components/verification/VideoVerificationResultView";
import { GovernanceBadge } from "@/components/GovernanceBadge";
import { VerificationActions } from "@/components/VerificationActions";
import { claimFixture, videoFixture } from "@/components/verification/__tests__/verificationResultFixtures";

function nodeText(n: TestRenderer.ReactTestInstance | string): string {
  if (typeof n === "string") return n;
  return n.children.map((c) => nodeText(c as TestRenderer.ReactTestInstance | string)).join("");
}
async function flush() {
  for (let i = 0; i < 4; i += 1) {
    await act(async () => {
      await new Promise((r) => setTimeout(r, 0));
    });
  }
}
async function mount(el: ReactNode) {
  let r!: TestRenderer.ReactTestRenderer;
  await act(async () => {
    r = TestRenderer.create(el as never);
  });
  await flush();
  return r;
}
const text = (r: TestRenderer.ReactTestRenderer) => JSON.stringify(r.toJSON());
const buttonLabels = (r: TestRenderer.ReactTestRenderer) => r.root.findAll((n) => n.type === "button").map((b) => nodeText(b));
const hrefs = (r: TestRenderer.ReactTestRenderer) => r.root.findAll((n) => n.type === "a").map((n) => n.props.href as string);

let clipboardWrites: string[] = [];
beforeEach(() => {
  jest.clearAllMocks();
  clipboardWrites = [];
  Object.defineProperty(globalThis, "navigator", { configurable: true, value: { clipboard: { writeText: async (t: string) => void clipboardWrites.push(t) } } });
  jest.spyOn(globalThis, "fetch" as never).mockImplementation((() => {
    throw new Error("the shared view must never fetch");
  }) as never);
  jest.spyOn(console, "error").mockImplementation(() => {});
});
afterEach(() => jest.restoreAllMocks());

function expectZeroSideEffects() {
  expect(mockedAuthedFetch).not.toHaveBeenCalled();
  expect(globalThis.fetch).not.toHaveBeenCalled();
  expect(mockedUseAuth).not.toHaveBeenCalled();
  expect(mockedUseUserPlan).not.toHaveBeenCalled();
  expect(mockedGenerateMemo).not.toHaveBeenCalled();
  expect(mockedDownloadTextFile).not.toHaveBeenCalled();
  expect(clipboardWrites).toEqual([]);
  expect(console.error).not.toHaveBeenCalled();
}

const PERSONAL_CONTROLS = ["Copy verdict", "Export memo", "View audit trail", "Hide audit trail", "Copy as JSON", "Download .json", "Verify another"];

const VIEWS = [
  {
    kind: "Claim",
    render: (props: Record<string, unknown> = {}) => createElement(ClaimVerificationResultView as never, { data: claimFixture(), ...props } as never),
    content: ["This claim is supported by 1/2 models", "The Eiffel Tower was completed in 1889.", "Consensus score", "Where models agree", "Completion year is 1889", "Opening month", "Per-model evidence", "Claim verification results are generated by multiple AI language models"],
    slots: ["noticeSurface", "governanceSurface", "actionsSurface"],
  },
  {
    kind: "Video",
    render: (props: Record<string, unknown> = {}) => createElement(VideoVerificationResultView as never, { data: videoFixture(), ...props } as never),
    content: ["Authentic camera footage", "harbour-clip.mp4", "Consensus score", "Video details", "Metadata flags", "Consumer phone encoder", "Where models agree", "Per-model evidence", "Processing warnings", "Important Legal Notice"],
    slots: ["governanceSurface", "actionsSurface"],
  },
];

describe.each(VIEWS)("shared $kind result view", ({ kind, render, content, slots }) => {
  it("renders the stored result content with ZERO auth, governance, plan, export, clipboard or network side effects", async () => {
    const r = await mount(render());
    const t = text(r);
    for (const c of content) expect(t).toContain(c);
    expectZeroSideEffects();
  });

  it("mounts no Personal control, no governance badge and no Verify Another by default; the only links are the /terms legal links", async () => {
    const r = await mount(render());
    const labels = buttonLabels(r).join("|");
    for (const control of PERSONAL_CONTROLS) expect(labels).not.toContain(control);
    expect(r.root.findAllByType(GovernanceBadge)).toHaveLength(0);
    expect(r.root.findAllByType(VerificationActions)).toHaveLength(0);
    expect(hrefs(r)).toEqual(["/terms", "/terms"]);
    expect(text(r)).not.toContain("Audit trail");
  });

  it("per-model evidence expands locally with no side effect", async () => {
    const r = await mount(render());
    const toggle = r.root.findAll((n) => n.type === "button")[0];
    await act(async () => toggle.props.onClick());
    await flush();
    expect(text(r)).toContain(kind === "Claim" ? "Correct parts" : "Authenticity signals");
    expectZeroSideEffects();
  });

  it("an explicit caller surface renders exactly where supplied; absent surfaces render nothing", async () => {
    const surfaces = Object.fromEntries(slots.map((s) => [s, createElement("div", { "data-slot": s }, `SLOT:${s}`)]));
    const r = await mount(render(surfaces));
    for (const s of slots) expect(r.root.findAll((n) => n.props["data-slot"] === s)).toHaveLength(1);
    const bare = await mount(render());
    expect(text(bare)).not.toContain("SLOT:");
    expectZeroSideEffects();
  });
});

describe("slot placement matches the Personal layout", () => {
  it("Claim: notice before the verdict banner, governance inside the consensus card, actions right after the claim text", async () => {
    const r = await mount(createElement(ClaimVerificationResultView, {
      data: claimFixture(),
      noticeSurface: createElement("i", null, "NOTICE"),
      governanceSurface: createElement("i", null, "GOV"),
      actionsSurface: createElement("i", null, "ACTIONS"),
    }));
    const t = text(r);
    expect(t.indexOf("NOTICE")).toBeLessThan(t.indexOf("This claim is supported"));
    expect(t.indexOf("Consensus score")).toBeLessThan(t.indexOf("GOV"));
    expect(t.indexOf("GOV")).toBeLessThan(t.indexOf("The Eiffel Tower was completed in 1889."));
    expect(t.indexOf("The Eiffel Tower was completed in 1889.")).toBeLessThan(t.indexOf("ACTIONS"));
    expect(t.indexOf("ACTIONS")).toBeLessThan(t.indexOf("Agreement"));
  });

  it("Video: governance inside the consensus card, actions after warnings and before the legal notice", async () => {
    const r = await mount(createElement(VideoVerificationResultView, {
      data: videoFixture(),
      governanceSurface: createElement("i", null, "GOV"),
      actionsSurface: createElement("i", null, "ACTIONS"),
    }));
    const t = text(r);
    expect(t.indexOf("Consensus score")).toBeLessThan(t.indexOf("GOV"));
    expect(t.indexOf("GOV")).toBeLessThan(t.indexOf("harbour-clip.mp4"));
    expect(t.indexOf("Processing warnings")).toBeLessThan(t.indexOf("ACTIONS"));
    expect(t.indexOf("ACTIONS")).toBeLessThan(t.indexOf("Important Legal Notice"));
  });
});

describe("intrinsic stored-result helpers are pure", () => {
  it("audit-trail DETAILS render stored evidence only: no toggle, no JSON copy/download, zero side effects", async () => {
    const c = await mount(createElement(ClaimVerificationAuditTrailDetails, { data: claimFixture() }));
    expect(text(c)).toContain("Audit trail");
    expect(text(c)).toContain('"children":["88","/100"]');
    expect(buttonLabels(c)).toEqual([]);
    const v = await mount(createElement(VideoVerificationAuditTrailDetails, { data: videoFixture() }));
    expect(text(v)).toContain("Verification ID");
    expect(text(v)).toContain("harbour-clip.mp4");
    expect(buttonLabels(v)).toEqual([]);
    expectZeroSideEffects();
  });

  it("clipboard text builders only format; they never touch the clipboard", () => {
    expect(buildClaimVerdictClipboardText(claimFixture())).toContain("ConvergePanel — Claim result");
    expect(buildVideoVerdictClipboardText(videoFixture())).toContain("VIDEO VERIFICATION RESULT");
    expect(clipboardWrites).toEqual([]);
  });
});

describe("import boundary of the shared view modules", () => {
  it.each(["ClaimVerificationResultView.tsx", "VideoVerificationResultView.tsx"])("%s imports no Personal auth, network, governance, plan, export or routing module", (file) => {
    const source = fs.readFileSync(path.join(process.cwd(), "components/verification", file), "utf8");
    const imports = source.split("\n").filter((l) => /^\s*import\b|from\s+["']/.test(l)).join("\n");
    for (const forbidden of ["@/components/AuthProvider", "@/lib/client/authedFetch", "@/lib/verification/generateMemo", "@/components/GovernanceBadge", "@/components/VerificationActions", "@/hooks/useUserPlan", "next/navigation", "personalResearchHref", "@/components/governance"]) {
      expect(imports).not.toContain(forbidden);
    }
    expect(source).not.toMatch(/run-governance|\/api\/|authedFetch|navigator\.clipboard|useAuth\(/);
  });
});
