/** Appended to copied verification verdicts so recipients see limitations. */

export const VIDEO_VERDICT_CLIPBOARD_DISCLAIMER = `

⚠️ DISCLAIMER: This is an AI-assisted verification result, not forensic analysis.
Generated by general-purpose AI models with known limitations including false positives
and false negatives. Do not use as legal evidence or the sole basis for consequential
decisions. See convergepanel.com/terms for full terms.`;

export const CLAIM_VERDICT_CLIPBOARD_DISCLAIMER = `

⚠️ DISCLAIMER: This is an AI-assisted claim verification result, not expert fact-checking,
journalistic verification, or a legal determination of truth. AI models may hallucinate or
reason incorrectly. Do not use as legal evidence or the sole basis for consequential
decisions. See convergepanel.com/terms for full terms.`;
