/**
 * Export Generator Provenance — DOCX composer tests. Uses the REAL,
 * unmocked renderer (same discipline as the sibling
 * AdaptiveResearchDocxDocument.spec.ts) so assertions reflect actual
 * generated .docx content, including a direct read of `docProps/core.xml`
 * for the document-metadata privacy check (Step 15).
 */

import JSZip from "jszip";
import { AdaptiveResearchExportV1 } from "@/lib/adaptiveSchema/researchExport";
import { renderAdaptiveResearchDocxV1 } from "@/lib/docx/renderAdaptiveResearchDocx";
import { extractDocxText } from "./testUtils";

function baseRecord(overrides: Partial<AdaptiveResearchExportV1> = {}): AdaptiveResearchExportV1 {
  return {
    version: 1,
    exportId: "exp-prov-docx-1",
    runId: "run-prov-docx-1",
    schemaId: "comparison_matrix",
    schemaFamily: "milestone2",
    schemaVersion: 1,
    reportVersion: 1,
    createdAt: "2026-01-02T00:00:00.000Z",
    createdBy: "uid-should-never-render-into-docx",
    format: "docx",
    artifactStatus: "ready",
    classification: "internal",
    governanceStatusAtExport: { family: "milestone2", kind: "approved", isOwnerOverride: false },
    reportSnapshot: {
      question: "Test question?",
      models: [{ modelId: "chatgpt" as any, ok: true }],
      reportTypeLabel: "Comparison Report",
      consensusLevel: "moderate",
      sourceGroundingLevel: "strong",
      reportGeneratedAt: "2026-01-01T00:00:00.000Z",
      milestone2: {
        schemaId: "comparison_matrix",
        result: {},
        meta: {} as any,
        decisionReceipt: {
          conclusion: "Test conclusion text.",
          basis: [],
          assumptions: [],
          uncertainties: [],
          limitations: [],
          sources: [],
          sourceBacked: false,
          humanReviewNeeded: false,
        },
      },
    },
    exportMetadata: {
      exportId: "exp-prov-docx-1",
      runId: "run-prov-docx-1",
      schemaVersion: 1,
      exportedSections: ["reportSnapshot.milestone2"],
      createdAt: "2026-01-02T00:00:00.000Z",
      requestingUser: "uid-should-never-render-into-docx",
      finalReportVersion: 1,
    },
    ...overrides,
  };
}

describe("renderAdaptiveResearchDocxV1 — generator provenance (DOCX)", () => {
  it("renders 'Generated by' and 'Email' when the record has a frozen generatedBy", async () => {
    const record = baseRecord({ generatedBy: { displayName: "Yasin Warsame", maskedEmail: "ya***@gmail.com" } });
    const { bytes } = await renderAdaptiveResearchDocxV1(record);
    const text = await extractDocxText(bytes);
    expect(text).toContain("GENERATED BY");
    expect(text).toContain("Yasin Warsame");
    expect(text).toContain("EMAIL");
    expect(text).toContain("ya***@gmail.com");
  });

  it("renders only the displayName line, omits the Email line, when maskedEmail is null", async () => {
    const record = baseRecord({ generatedBy: { displayName: "ConvergePanel user", maskedEmail: null } });
    const { bytes } = await renderAdaptiveResearchDocxV1(record);
    const text = await extractDocxText(bytes);
    expect(text).toContain("ConvergePanel user");
    expect(text).not.toContain("EMAIL");
  });

  it("V1 compatibility: renders nothing extra (no 'Generated by' label at all) when generatedBy is absent", async () => {
    const record = baseRecord(); // no generatedBy override
    const { bytes } = await renderAdaptiveResearchDocxV1(record);
    const text = await extractDocxText(bytes);
    expect(text).not.toContain("GENERATED BY");
  });

  it("privacy: never renders the raw uid anywhere in the visible document text", async () => {
    const record = baseRecord({ generatedBy: { displayName: "Yasin Warsame", maskedEmail: "ya***@gmail.com" } });
    const { bytes } = await renderAdaptiveResearchDocxV1(record);
    const text = await extractDocxText(bytes);
    expect(text).not.toContain("uid-should-never-render-into-docx");
  });

  it("privacy: never renders the full unmasked email in the visible document text", async () => {
    const record = baseRecord({ generatedBy: { displayName: "Yasin Warsame", maskedEmail: "ya***@gmail.com" } });
    const { bytes } = await renderAdaptiveResearchDocxV1(record);
    const text = await extractDocxText(bytes);
    expect(text).not.toContain("yasinwarsame@gmail.com");
  });

  it("document metadata (docProps/core.xml): creator stays 'ConvergePanel', never the generator's name/email or the raw uid — no hidden metadata leak", async () => {
    const record = baseRecord({ generatedBy: { displayName: "Yasin Warsame", maskedEmail: "ya***@gmail.com" } });
    const { bytes } = await renderAdaptiveResearchDocxV1(record);
    const zip = await JSZip.loadAsync(bytes);
    const coreXml = await zip.files["docProps/core.xml"].async("string");
    expect(coreXml).toContain("ConvergePanel");
    expect(coreXml).not.toContain("Yasin Warsame");
    expect(coreXml).not.toContain("ya***@gmail.com");
    expect(coreXml).not.toContain("yasinwarsame@gmail.com");
    expect(coreXml).not.toContain("uid-should-never-render-into-docx");
  });

  it("also confirms no email/uid leaked into any other package-level XML (app.xml / custom properties, if present)", async () => {
    const record = baseRecord({ generatedBy: { displayName: "Yasin Warsame", maskedEmail: "ya***@gmail.com" } });
    const { bytes } = await renderAdaptiveResearchDocxV1(record);
    const zip = await JSZip.loadAsync(bytes);
    for (const [name, file] of Object.entries(zip.files)) {
      if (file.dir || !name.endsWith(".xml")) continue;
      const content = await file.async("string");
      expect(content).not.toContain("yasinwarsame@gmail.com");
      expect(content).not.toContain("uid-should-never-render-into-docx");
    }
  });

  it("layout: works correctly with a long display name and long email domain (no crash, both render)", async () => {
    const record = baseRecord({
      generatedBy: { displayName: "Alexandria Montgomery-Fitzgerald the Third of Testington", maskedEmail: "al***@a-very-long-enterprise-subdomain.example.co.uk" },
    });
    const { bytes } = await renderAdaptiveResearchDocxV1(record);
    const text = await extractDocxText(bytes);
    expect(text).toContain("Alexandria Montgomery-Fitzgerald the Third of Testington");
    expect(text).toContain("al***@a-very-long-enterprise-subdomain.example.co.uk");
  });
});
