/**
 * Terms of Service Page
 * 
 * Basic terms of service for ConvergePanel.
 * This is a draft that should be reviewed by legal counsel before production launch.
 */

import Link from "next/link";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-slate-50 py-10 px-4">
      <div className="max-w-3xl mx-auto">
        <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-8">
          <h1 className="text-3xl font-semibold text-slate-900 mb-6">Terms of Service</h1>
          
          <div className="prose prose-slate max-w-none">
            <p className="text-sm text-slate-600 mb-6">
              <strong>Last updated:</strong> {new Date().toLocaleDateString()}
            </p>

            <section className="mb-8">
              <h2 className="text-xl font-semibold text-slate-900 mb-3">1. Introduction</h2>
              <p className="text-slate-700 mb-3">
                Welcome to ConvergePanel. These Terms of Service ("Terms") govern your use of our
                service that allows you to query multiple AI models and receive unified responses.
              </p>
              <p className="text-slate-700">
                This is an early-stage product. By using ConvergePanel, you agree to these Terms.
                If you do not agree, please do not use the service.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold text-slate-900 mb-3">2. Service Description</h2>
              <p className="text-slate-700 mb-3">
                ConvergePanel sends your questions to multiple third-party AI models (including but
                not limited to OpenAI's ChatGPT, Anthropic's Claude, X.AI's Grok, and Perplexity)
                and synthesizes their responses into a unified answer.
              </p>
              <p className="text-slate-700">
                We are not responsible for the accuracy, completeness, or reliability of responses
                generated by these third-party AI models. You use the service at your own risk.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold text-slate-900 mb-3">3. Usage Limits</h2>
              <p className="text-slate-700 mb-3">
                Free plan users are subject to monthly usage limits. We reserve the right to modify
                these limits at any time. Paid plans may have different limits (coming soon).
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold text-slate-900 mb-3">4. User Responsibilities</h2>
              <p className="text-slate-700 mb-3">
                You are responsible for:
              </p>
              <ul className="list-disc list-inside text-slate-700 mb-3 space-y-1">
                <li>Maintaining the security of your account</li>
                <li>Using the service in compliance with applicable laws</li>
                <li>Not using the service for illegal or harmful purposes</li>
                <li>Not attempting to circumvent usage limits or security measures</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold text-slate-900 mb-3">5. Third-Party Services</h2>
              <p className="text-slate-700 mb-3">
                ConvergePanel uses third-party AI services. Your use of these services is also
                subject to their respective terms of service:
              </p>
              <ul className="list-disc list-inside text-slate-700 mb-3 space-y-1">
                <li><a href="https://openai.com/policies/terms-of-use" target="_blank" rel="noopener noreferrer" className="text-sky-600 hover:underline">OpenAI Terms of Use</a></li>
                <li><a href="https://www.anthropic.com/legal/terms" target="_blank" rel="noopener noreferrer" className="text-sky-600 hover:underline">Anthropic Terms of Service</a></li>
                <li><a href="https://x.ai/legal/terms" target="_blank" rel="noopener noreferrer" className="text-sky-600 hover:underline">X.AI Terms of Service</a></li>
                <li><a href="https://www.perplexity.ai/terms" target="_blank" rel="noopener noreferrer" className="text-sky-600 hover:underline">Perplexity Terms of Service</a></li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold text-slate-900 mb-3">6. AI-Generated Trust &amp; Readiness Indicators</h2>
              <p className="text-slate-700 mb-3">
                ConvergePanel may display trust signals, readiness indicators, verification
                gates, consensus assessments, bias flags, and similar outputs ("Indicators").
                These Indicators are heuristic, rules-based assessments generated from
                comparisons across multiple AI model responses. They are provided for
                informational and decision-support purposes only.
              </p>
              <p className="text-slate-700 mb-3">
                Indicators do not constitute factual certification, legal approval, compliance
                clearance, financial advice, medical guidance, or authorization to act. No
                Indicator should be interpreted as a guarantee of accuracy, completeness, or
                fitness for any particular purpose.
              </p>
              <p className="text-slate-700">
                You remain solely responsible for independent review, validation, and any
                decisions made using platform outputs. ConvergePanel expressly disclaims
                liability for actions taken in reliance on any Indicator.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold text-slate-900 mb-3">7. Limitation of Liability</h2>
              <p className="text-slate-700 mb-3">
                ConvergePanel is provided &ldquo;as is&rdquo; without warranties of any kind,
                express or implied. We are not liable for any direct, indirect, incidental, or
                consequential damages arising from your use of the service, including but not
                limited to decisions made based on AI-generated responses or trust indicators.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold text-slate-900 mb-3">8. Changes to Terms</h2>
              <p className="text-slate-700">
                We may update these Terms at any time. Continued use of the service after changes
                constitutes acceptance of the new Terms.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold text-slate-900 mb-3">9. Contact</h2>
              <p className="text-slate-700">
                If you have questions about these Terms, please contact us at{" "}
                <a href="mailto:support@convergepanel.com" className="text-sky-600 hover:underline">
                  support@convergepanel.com
                </a>.
              </p>
            </section>
          </div>

          <div className="mt-8 pt-6 border-t border-slate-200">
            <Link
              href="/"
              className="text-sm text-sky-600 hover:text-sky-700 font-medium"
            >
              ← Back to ConvergePanel
            </Link>
          </div>
        </div>
      </div>
    </main>
  );
}

