/**
 * Synthesis layer: structured report schema, evidence packing, and transforms.
 */

import { z } from "zod";

/**
 * Structured Synthesis Schema (New Format)
 * 
 * Research-worthy synthesis report generated by GPT-5.1.
 * This is the canonical format - strict JSON, no HTML, no legacy strings.
 */
const KeyFindingSupportSchema = z.object({
  supportingModels: z.array(z.string()),
  dissentingModels: z.array(z.string()),
  unknownModels: z.array(z.string()),
  supportRatio: z.number(),
  confidenceLabel: z.enum(["High", "Medium", "Low"]),
});

export const StructuredSynthesisSchema = z.object({
  executiveSummary: z.string(),
  keyFindings: z.array(z.object({
    claim: z.string(),
    confidence: z.enum(["High", "Medium", "Low", "Mixed"]),
    evidenceRefs: z.array(z.string()).default([]),
    modelsSupporting: z.array(z.string()).min(1),
    /** Deterministic post-pass: model stance vs claim anchors (optional on LLM output). */
    support: KeyFindingSupportSchema.optional(),
    /** Claim-level evidence strength vs model support (optional on LLM output). */
    evidenceQuality: z.enum(["strong", "mixed", "weak"]).optional(),
  })),
  disagreements: z.array(z.object({
    topic: z.string(),
    positionsByModel: z.record(z.string(), z.string()), // Record<modelId, position>
    whyTheyDiffer: z.string(),
  })).default([]),
  biasAndBlindSpots: z.array(z.object({
    biasType: z.string(),
    description: z.string(),
    modelsImplicated: z.array(z.string()).min(1),
    evidence: z.array(z.object({
      modelId: z.string(),
      excerpt: z.string().max(240),
      rationale: z.string(),
    })).min(1),
    likelyCauses: z.array(z.string()).default([]),
    impact: z.string(),
    mitigationSteps: z.array(z.string()).default([]),
  })).default([]),
  openQuestions: z.array(z.string()).default([]),
  methodology: z.string(),
});

export type StructuredSynthesis = z.infer<typeof StructuredSynthesisSchema>;

