/**
 * Export Generator Provenance — email masking for the "Generated by /
 * Email" block frozen into every Adaptive Research Export (PDF/DOCX/JSON).
 *
 * Deliberately a SEPARATE utility from `lib/utils/maskEmail.ts`, not a
 * reuse of it, for two reasons:
 * 1. `maskEmail()` reveals the first 3 local-part characters (pinned by
 *    existing governance-identity tests — "jane" → "jan***", "sarah" →
 *    "sar***"). This feature's product spec calls for exactly 2:
 *    "mike@company.com" → "mi***@company.com",
 *    "yasinwarsame@gmail.com" → "ya***@gmail.com". Changing the shared
 *    3-char rule would silently alter governance UI output it was never
 *    asked to change.
 * 2. `maskEmail()` has a "never mask the CURRENT viewer's own email"
 *    exception (reveals the full address when it matches `currentUserEmail`)
 *    — correct for governance UI (a reviewer/owner viewing their OWN
 *    identity in a list should see it unmasked), but WRONG here: export
 *    provenance is the exporting user's OWN email, masked by default for
 *    everyone who later opens the document, including that same user.
 *    There is no "unmask for the current viewer" concept for a static,
 *    frozen, downloadable file.
 *
 * Rule: reveal the first 2 local-part characters (or the whole local part
 * if it has 2 or fewer characters), then "***@domain". Domain is always
 * shown in full. Never throws — malformed/missing input returns `null`.
 */
export function maskEmailForExportProvenance(email: string | null | undefined): string | null {
  const trimmed = (email ?? "").trim();
  if (!trimmed) return null;

  const at = trimmed.indexOf("@");
  if (at <= 0) return null; // no "@", or "@" is the very first character (no local part)

  const local = trimmed.slice(0, at);
  const domain = trimmed.slice(at + 1);
  if (!local || !domain) return null;

  const revealed = local.length <= 2 ? local : local.slice(0, 2);
  return `${revealed}***@${domain}`;
}
