/**
 * Export Generator Provenance — resolves and freezes the identity of the
 * authenticated person who generated an Adaptive Research Export
 * (PDF/DOCX/JSON), per the product requirement that exported documents
 * identify their generator without exposing internal identifiers.
 *
 * FROZEN AT EXPORT-CREATION TIME ONLY (critical historical invariant): this
 * resolver is called exactly once, in `POST /api/user/runs/[runId]/export`,
 * at the moment the export record is created, using the uid already
 * authenticated for that request — never accepted from the client body.
 * The resulting `{displayName, maskedEmail}` is baked into the persisted
 * `AdaptiveResearchExportV1` record (`generatedBy` field) and every
 * downstream reader (PDF/DOCX/JSON composers, the historical regeneration
 * route `GET /api/user/runs/[runId]/exports/[exportId]`) reads it straight
 * off the frozen record — this module is never imported by, and this
 * function is never called from, any regeneration path. If the account's
 * name/email changes later, or the account is deleted, an already-created
 * export's provenance block is completely unaffected — it already has its
 * own frozen copy, exactly like `reportSnapshot`'s "no live lookup on
 * regeneration" guarantee (see researchExport.ts's header comment).
 *
 * Never persists a raw Firebase UID or unmasked email in this shape —
 * only a human-facing display name and an already-masked email string.
 * Mirrors the existing `resolveReviewerDisplayName`
 * (lib/governance/reviewerIdentity.ts) fallback discipline (name, else
 * masked email, else a safe neutral label — never a blank string, never a
 * raw uid) but is intentionally NOT that function, reused: this needs both
 * the display name AND the masked email as two separate, always-present-or-
 * null fields (a report's "Generated by" / "Email" are two distinct lines),
 * while `resolveReviewerDisplayName` collapses to one string. Also, this is
 * always the CALLER's own identity (no "mask unless it's the viewer" case
 * ever applies — see maskEmailForExportProvenance.ts's own doc comment).
 */

import "server-only";
import { adminDb } from "@/lib/firebase/admin";
import { maskEmailForExportProvenance } from "@/lib/utils/maskEmailForExportProvenance";

export const EXPORT_GENERATED_BY_NEUTRAL_FALLBACK = "ConvergePanel user";

export interface AdaptiveExportGeneratedBy {
  /** Preferred: the account's own display name. Falls back to the masked email, then to a neutral safe label. Never a raw UID, never blank. */
  displayName: string | null;
  /** Already masked (see maskEmailForExportProvenance.ts) — `null` only when the account genuinely has no usable email on file. Never the unmasked address. */
  maskedEmail: string | null;
}

/**
 * Never throws — a Firestore read failure or a missing/malformed
 * `users/{uid}` document degrades to the neutral fallback, exactly like
 * every other identity resolver in this codebase (reviewerIdentity.ts's
 * own doc comment: "never throws... degrades... rather than an empty
 * string").
 */
export async function resolveExportGeneratedBy(uid: string): Promise<AdaptiveExportGeneratedBy> {
  if (!adminDb) return { displayName: EXPORT_GENERATED_BY_NEUTRAL_FALLBACK, maskedEmail: null };

  try {
    const snap = await adminDb.collection("users").doc(uid).get();
    const data = snap.data();
    const rawName = typeof data?.name === "string" ? data.name.trim() : "";
    const rawEmail = typeof data?.email === "string" ? data.email.trim() : "";

    const maskedEmail = maskEmailForExportProvenance(rawEmail);
    const displayName = rawName || maskedEmail || EXPORT_GENERATED_BY_NEUTRAL_FALLBACK;

    return { displayName, maskedEmail };
  } catch {
    return { displayName: EXPORT_GENERATED_BY_NEUTRAL_FALLBACK, maskedEmail: null };
  }
}
