/**
 * Adaptive Result Schema System — Core Types
 *
 * Two-stage design:
 * 1. classifyQuery() tags a query with a QueryClassification (epistemic type).
 * 2. SCHEMA_REGISTRY maps each QueryType to a ResultSchema that drives both
 *    the per-model prompt (promptBuilder.ts) and the comparison renderer
 *    (components/adaptive/*).
 *
 * Sections are never optional within a schema — optionality is resolved by
 * choosing a different schema, not by letting models emit empty headers.
 */

import { ModelId } from "@/lib/types";

export type QueryType =
  | "contested_empirical"
  | "legal_regulatory"
  | "financial_valuation"
  | "factual_lookup"
  | "procedural"
  | "medical_health"
  | "forecast_speculative"
  | "creative_generative"
  | "generic";

export type AnswerShape =
  | "consensus_map"
  | "rule_application"
  | "metrics_grid"
  | "verdict_card"
  | "step_diff"
  | "evidence_tiers"
  | "scenario_tree"
  | "gallery"
  | "generic_sections";

export interface QueryClassification {
  queryType: QueryType;
  domain: string;
  answerShape: AnswerShape;
  quantExpected: boolean;
  timeSensitivity: "low" | "medium" | "high";
  userIntent:
    | "understand_debate"
    | "get_answer"
    | "make_decision"
    | "learn_process"
    | "generate_content";
  confidence: number;
}

// ─── Atomic comparable units ───────────────────────────────────────────────

export type ClaimStance = "asserts" | "disputes" | "uncertain";
export type ClaimConfidence = "settled" | "majority_view" | "contested" | "speculative";
export type ClaimEvidenceType = "empirical" | "theoretical" | "anecdotal" | "authoritative";

export interface Claim {
  /** Short kebab-case slug generated by the model, e.g. "demand-pull-driver". */
  id: string;
  /** One sentence, max 25 words. */
  claim: string;
  stance: ClaimStance;
  confidence: ClaimConfidence;
  evidenceType: ClaimEvidenceType;
  /** For contested claims: the competing positions. */
  camps?: { label: string; position: string }[];
}

export interface Metric {
  label: string;
  value: number | null;
  unit: string;
  /** ISO date or "unknown". */
  asOf: string;
  source: string;
}

export interface Step {
  order: number;
  /** Max 20 words. */
  action: string;
  prerequisite?: string;
  failureMode?: string;
}

export interface Scenario {
  label: string;
  /** 0–1, must sum ≈ 1 across scenarios in a single response. */
  probability: number;
  /** Max 60 words. */
  narrative: string;
  /** Falsifiable signals, max 3. */
  leadingIndicators: string[];
}

// ─── Field / schema definitions ────────────────────────────────────────────

export type FieldType =
  | "string"
  | "string[]"
  | "claim[]"
  | "metric[]"
  | "step[]"
  | "scenario[]";

export interface FieldSpec {
  key: string;
  type: FieldType;
  /** Hard cap, enforced in prompt AND validated post-hoc. */
  maxWords?: number;
  maxItems?: number;
  /** Minimum items, when the schema requires a range (e.g. scenarios 2-4). */
  minItems?: number;
  /** Injected into the model prompt verbatim. */
  description: string;
  /** Restricts which values are valid for this claim-like field (schema-specific confidence vocab). */
  allowedConfidenceValues?: ClaimConfidence[];
}

export interface ResultSchema {
  id: QueryType;
  /** What the list view collapses to. */
  headlineField: string;
  renderHint: AnswerShape;
  fields: FieldSpec[];
}

// ─── Per-model adaptive result ─────────────────────────────────────────────

/**
 * Successfully parsed + validated adaptive payload for one model.
 * Keys mirror the schema's fields; values are typed per FieldSpec.type.
 */
export type AdaptiveFieldValue =
  | string
  | string[]
  | Claim[]
  | Metric[]
  | Step[]
  | Scenario[];

export interface AdaptiveModelResult {
  modelId: ModelId;
  schemaId: QueryType;
  /** True when JSON parsed and validated cleanly (possibly with soft-truncation). */
  ok: boolean;
  data: Record<string, AdaptiveFieldValue> | null;
  /** Populated when ok === false — render as a failed cell, never crash the comparison. */
  parseError?: string;
  /** Field keys that were soft-truncated (word/item cap exceeded). */
  truncatedFields?: string[];
}

// ─── Claim alignment (Phase 4b) ────────────────────────────────────────────

/**
 * A cell's stance RELATIVE TO the cluster's canonical proposition — distinct
 * from Claim.stance (ClaimStance), which is the model's own raw assertion
 * polarity independent of any cluster. Two claims with opposite ClaimStance
 * values about the same proposition are exactly the case this type exists to
 * represent in one row: e.g. "cap-and-trade achieves similar reductions"
 * (rawStance: asserts) and "carbon taxes often outperform ETS" (rawStance:
 * asserts) resolve to relative stances "agrees" / "disputes" against a
 * neutral canonicalText like "relative effectiveness of carbon pricing
 * mechanisms".
 */
export type ClaimCellStance = "agrees" | "disputes" | "partial" | "unclear";

export interface AlignedClaimCell {
  modelId: ModelId;
  /** Stance relative to the cluster's canonicalText — drives agreement scoring and matrix coloring. */
  stance: ClaimCellStance;
  /** The model's own original assertion polarity, kept for audit/debugging. */
  rawStance: ClaimStance;
  confidence: ClaimConfidence;
  /** Carried through from the source Claim when present — lets consensus_map expand disputed rows. */
  camps?: { label: string; position: string }[];
  /** The model's own wording (verbatim claim text, or a short paraphrase from the backfill pass) — feeds "Show Positions". */
  excerpt: string;
  /** Only set for claim[]-derived cells — feeds medical_health's evidence-tier-weighted scoring. */
  evidenceType?: ClaimEvidenceType;
  /**
   * True when this cell came from the stance-extraction backfill pass (the
   * model never emitted a claim that clustered here directly, but a
   * dedicated check found it does take a position) rather than from the
   * model's own clustered claim. Backfilled cells default to
   * confidence "majority_view" since it's an inferred position, not the
   * model's stated one.
   */
  backfilled?: boolean;
  /**
   * The structured source value for rows built by a non-claim unitizer
   * (fieldAlignment.ts: metrics/steps/scenarios) — lets schema-specific
   * AgreementComparators (agreementComparators.ts) do numeric/order math
   * without re-parsing `excerpt` text. Absent for claim[]-derived rows.
   */
  raw?: Metric | Step | Scenario;
}

export type AlignedClaimStatus = "consensus" | "majority" | "split" | "single_source";

export interface AlignedClaim {
  /** Canonical id — derived from the cluster's canonicalText, or a generated cluster id. */
  id: string;
  /** Canonical, neutral proposition text for the cluster (not biased toward any one model's phrasing). */
  claimText: string;
  /** One entry per model in the run; null = model truly never took a position on this proposition. */
  cells: Array<AlignedClaimCell | null>;
  /** 0–1, schema-adaptive agreement score — computed by the AgreementComparator (see agreementComparators.ts), not by alignment itself. Defaults to 0 until scored. */
  agreementScore: number;
  /** 0–1, see scoring.ts. Defaults to 0 until scored. */
  certaintyScore: number;
  /** Defaults to "single_source" until scored; recomputed from agreementScore + coverage. */
  status: AlignedClaimStatus;
  /**
   * Schema-specific disagreement classification beyond the generic status
   * enum — e.g. legal_regulatory's "jurisdiction_mismatch", which is a hard
   * key violation and must never be averaged into agreementScore like an
   * ordinary split.
   */
  disagreementType?: string;
}

// ─── Verification gate + synthesis report (R1d/R1e) ────────────────────────
// Declared here (not in gate.ts/synthesisReport.ts, which are "server-only")
// so client components (components/adaptive/*) can import these shapes
// without risking a server-only module ending up in a client bundle.

export type AdaptiveGateStatus = "pass" | "caution" | "fail";

export interface AdaptiveGateResult {
  status: AdaptiveGateStatus;
  runCertainty: number;
  loadBearingSplitCount: number;
  loadBearingClaims: AlignedClaim[];
}

export interface AdaptiveSynthesisReport {
  unifiedAnswer: string;
  panelVerdict: string;
  gate: AdaptiveGateStatus;
  runCertainty: number;
  whereModelsAgree: string[];
  whereModelsDisagree: string[];
  certaintyAssessment: string;
  narrativeSections: { title: string; body: string }[];
  degraded: boolean;
}

// ─── Trust Summary (R1c) ────────────────────────────────────────────────
// Declared here for the same reason as the gate/synthesis-report shapes
// above: client components (components/adaptive/*) render this directly.

export interface ModelTrustSummary {
  modelId: ModelId;
  /** Count of claim[]/metric[]/step[]/scenario[] items this model raised in its own response. */
  claimsContributed: number;
  /** 0–1: fraction of comparable rows where this model's stance matched the row's majority stance. 1 when the model had no comparable rows. */
  majorityAlignment: number;
  /** 0–1: fraction of sourceable fields (Metric.source, factual_lookup's `source`) with a real, non-generic source. 1 when the schema has no sourceable field. */
  citationScore: number;
  /** Count of rows where this model disputed a row that the panel otherwise resolved as "split". */
  contradictionCount: number;
  parseHealth: "ok" | "degraded" | "failed";
  /** 0–1 composite: citation/consistency/contradiction weighted per TRUST_WEIGHTS_BY_SCHEMA. 0 when parseHealth is "failed". */
  trustScore: number;
}

export interface AdaptiveTrustSummary {
  perModel: ModelTrustSummary[];
  /** Mean trustScore across models with parseHealth !== "failed"; 0 if every model failed to parse. */
  overallTrust: number;
}
