/**
 * Adaptive Research Export, Phase 2 — GET /api/user/runs/[runId]/exports.
 * Lists export records for a run, newest `reportVersion` first,
 * metadata only (Part 3 — never the full frozen `reportSnapshot`; that only
 * ever leaves the server as a rendered file, via the regeneration route).
 *
 * Flow: authenticate → load run → authorize access to run → check
 * ADAPTIVE_RESEARCH_EXPORT_ENABLED → list export records (paginated) →
 * project to metadata-only DTOs → return, newest first.
 *
 * Deliberately does NOT re-run `canExportAdaptiveResearch()` here — this
 * endpoint is a read of the run owner's own export history, gated on run
 * ownership + the feature flag, same as `GET /api/user/runs/[runId]`
 * itself. Per-item export/regeneration authorization (plan, governance
 * state) is evaluated by the regeneration route when an item is actually
 * opened, not here — this list is metadata, not report content.
 *
 * Phase 5 (Part 14) — cursor-based pagination. `?cursor=<reportVersion>`
 * from the previous page's `nextCursor` fetches the next page (strictly
 * older exports); omit for the first page. `?limit=` is optional and
 * clamped server-side by `listAdaptiveExportRecords` regardless of what a
 * caller requests — a client can never force an unbounded read.
 */

import { NextRequest, NextResponse } from "next/server";
import { resolveRequestIdentity } from "@/lib/auth/resolveRequestIdentity";
import { logIdentityResolutionFailure } from "@/lib/auth/identityResolutionTelemetry";
import { adminDb } from "@/lib/firebase/admin";
import { ADAPTIVE_RESEARCH_EXPORT_ENABLED } from "@/lib/env";
import { listAdaptiveExportRecords } from "@/lib/firestore/adaptiveExports";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

async function getUid(req: NextRequest): Promise<string | NextResponse> {
  const identity = await resolveRequestIdentity(req);
  if (identity.status === "authenticated") return identity.uid;
  logIdentityResolutionFailure({ route: "GET /api/user/runs/[runId]/exports", method: "GET", failureCategory: identity.reason });
  if (identity.reason === "missing_credentials") {
    return NextResponse.json({ ok: false, errorCode: "unauthorized", message: "Please sign in." }, { status: 401 });
  }
  return NextResponse.json({ ok: false, errorCode: "auth_error", message: "Authentication failed." }, { status: 401 });
}

function errorResponse(status: number, errorCode: string, message: string) {
  return NextResponse.json({ ok: false, errorCode, message }, { status });
}

export interface AdaptiveExportListItem {
  exportId: string;
  reportVersion: number;
  schemaId: string;
  schemaFamily: "milestone2" | "legacy";
  format: string;
  artifactStatus: string;
  createdAt: string;
  createdBy: string;
  governanceStatusAtExport: unknown;
  classification: string;
  /**
   * Phase 5 (Part 4/5) — the sha256 of this export's generated bytes,
   * computed at generation time and already persisted on
   * `exportMetadata.fileHash` since Phase 1; simply exposed here now.
   * Absent for "generating"/"failed" records (no bytes were ever produced).
   * For PDF/JSON this hash is fully reproducible by regenerating the same
   * frozen record. For DOCX it is NOT reproducible across renders (the
   * `docx` library stamps `docProps/core.xml` timestamps unconditionally)
   * — present for reference/logging, never usable as a DOCX
   * byte-for-byte-identity check. See docs/adaptive-research-export-architecture.md.
   */
  fileHash?: string;
  hashAlgorithm?: "sha256";
}

export async function GET(req: NextRequest, context: { params: Promise<{ runId: string }> }) {
  const uidOrRes = await getUid(req);
  if (uidOrRes instanceof NextResponse) return uidOrRes;
  const uid = uidOrRes;

  if (!ADAPTIVE_RESEARCH_EXPORT_ENABLED) {
    return errorResponse(404, "not_found", "Not found.");
  }

  const { runId } = await context.params;
  if (!runId?.trim() || !adminDb) {
    return errorResponse(404, "not_found", "Run not found.");
  }

  const snap = await adminDb.collection("runs").doc(runId).get();
  if (!snap.exists) {
    return errorResponse(404, "not_found", "Run not found.");
  }
  const data = snap.data() as Record<string, unknown>;
  const owner = String(data.userId ?? "");
  if (owner !== uid) {
    return errorResponse(403, "forbidden", "You do not have access to this run.");
  }

  const cursorParam = req.nextUrl.searchParams.get("cursor");
  const limitParam = req.nextUrl.searchParams.get("limit");
  const beforeReportVersion = cursorParam !== null && !Number.isNaN(Number(cursorParam)) ? Number(cursorParam) : undefined;
  const limit = limitParam !== null && !Number.isNaN(Number(limitParam)) ? Number(limitParam) : undefined;

  const listResult = await listAdaptiveExportRecords(runId, { limit, beforeReportVersion });
  if (!listResult.ok) {
    return errorResponse(500, "list_failed", "Could not load export history. Please try again.");
  }

  const items: AdaptiveExportListItem[] = listResult.records.map((r) => ({
    exportId: r.exportId,
    reportVersion: r.reportVersion,
    schemaId: r.schemaId,
    schemaFamily: r.schemaFamily,
    format: r.format,
    artifactStatus: r.artifactStatus,
    createdAt: r.createdAt,
    createdBy: r.createdBy,
    governanceStatusAtExport: r.governanceStatusAtExport,
    classification: r.classification,
    ...(r.exportMetadata.fileHash ? { fileHash: r.exportMetadata.fileHash, hashAlgorithm: "sha256" as const } : {}),
  }));

  const nextCursor = listResult.hasMore && items.length > 0 ? items[items.length - 1].reportVersion : null;

  return NextResponse.json({ ok: true, runId, exports: items, hasMore: listResult.hasMore, nextCursor });
}
